insert into `Drug Company` (drug_company_id, drug_company_name) values (1, 'Ultradent Products, Inc.');
insert into `Drug Company` (drug_company_id, drug_company_name) values (2, 'Harmon Stores Inc');
insert into `Drug Company` (drug_company_id, drug_company_name) values (3, 'Wal-Mart Stores Inc');
insert into `Drug Company` (drug_company_id, drug_company_name) values (4, 'Cadila Healthcare Limited');
insert into `Drug Company` (drug_company_id, drug_company_name) values (5, 'Energizer Personal Care LLC');
insert into `Drug Company` (drug_company_id, drug_company_name) values (6, 'Henry Schein, Inc.');
insert into `Drug Company` (drug_company_id, drug_company_name) values (7, 'Family Dollar');
insert into `Drug Company` (drug_company_id, drug_company_name) values (8, 'Three Rivers Pharmaceuticals, LLC.');
insert into `Drug Company` (drug_company_id, drug_company_name) values (9, 'Save-A-Lot Food Stores Ltd');
insert into `Drug Company` (drug_company_id, drug_company_name) values (10, 'Agile Pharmachem');
